### PR TITLE
autoGrow now recognises numpad 0 as printable

### PR DESCRIPTION
**Pull request by kivikakk**
keyCode as given to the keydown event doesn't mimic ASCII; see http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes.

Previously, due to chance overlap with the range for lowercase letters (which aren't a thing in keyCode land), we missed keyCode 96 (numpad 0), which under Firefox (!), would cause it not to be inputtable at all.

### CODE REVIEW

**Comment by kivikakk** [comment]
Closing PR as this repo is probably unmaintained.

**Comment by joallard** [comment]
It's not, maintenance is just under heavy load. Issues and PRs are prioritized namely based on votes, number of comments and confirmation.

**Comment by kivikakk** [comment]
@joallard: my bad, I was just closing out old PRs of mine and assumed this was as the others.

**Comment by kivikakk** [comment]
Resolved merge conflicts.

**Comment by kivikakk** [comment]
🎉

**Pull request merged**
