### PR TITLE
No need to remove the selected item matching if there is no input

### PR DESCRIPTION
**Pull request by ghoshnirmalya**
Return false from `removeItem` if there is no input.

### CODE REVIEW

**Comment by joallard** [comment]
Thanks. Can you explain a short example where that case would happen?

**Comment by ghoshnirmalya** [comment]
I'm using this Ember plugin (https://github.com/miguelcobain/ember-cli-selectize). 

So, whenever I'm using the select box in a page and going to the next route, it throws me this error `Uncaught TypeError: Cannot read property 'attr' of null`. I found out that the issue was coming from this line: `value = hash_key($item.attr('data-value'));` when the `value` argument in this line `removeItem: function(value, silent) {` becomes `null`.

**Comment by joallard** [comment]
Okay, interesting, and who calls `removeItem` with a `null`?

**Comment by ghoshnirmalya** [comment]
This line calls it: `self.trigger('option_remove', value);`

**Comment by joallard** [comment]
Line 1343 in `removeOption`, `self.trigger('option_remove', value);`, does not call `removeItem`.

**Comment by ghoshnirmalya** [comment]
this line (https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L1335) calls it.

**Comment by jakeonfire** [comment]
@ghoshnirmalya i got that error too with `ember-cli-selectize` when trying to use `content.name` for the `optionValuePath`. i changed it to `content.id` and no longer get that error. might have something to do with your computed `optionValuePath`s changing? hope that helps. (actually created a mixin that adds a `selectizeId` to any model so that i can also use newly created items which caches a random-ish ID for selectize's use)

**Pull request closed without merging**
