### PR TITLE
Plugin to make the selectize read-only

### PR DESCRIPTION
**Pull request by ggets**

### CODE REVIEW

**Comment by fabienwnklr** [comment]
an option `search: true/false` already exists, why do this as a plugin ?

**Comment by ggets** [comment]
I can't seem to find that option, please point me to it. This functionality is meant to be more like the lock(). The major benefit is that it is logically more compatible with html and css mainly because of the `readonly` attribute.

**Comment by ggets** [comment]
The other benefit is that making it readonly doesn't allow user focus on the field which is rather confusing anyway on a input that is not allowed to be edited IMHO.

**Comment by risadams** [comment]
I think it is a great plugin, I'm going to add some tests/examples and consider making it available in general

**Review by risadams — APPROVED** [review]

**Pull request merged**
