### PR TITLE
Allow the users to type in selectize single selects.

### PR DESCRIPTION
**Pull request by luanfonceca**
This "PR" refers to #647, I will be glad if you guys have other thoughts on how i did that and sorry for taking so long to do this.

o/

### CODE REVIEW

**Comment by dcramble** [comment]
I really like what you have done hear, I have been use this plugin for a few months now.

One issue I'm running into, is the user clicking on the selector after the value has been set, but not actually changing the value, which seems to trigger a "change" event.

This seems to happen when a user sets the value in the selector, then changes the value in a field to the left of, or any field with a preceding tab order, and tabs out of said field. When they tab out, they land on the already set selctor and this triggers a change event, even though the data is not changed by the user.

If you have events wired to the change handler, they fire and issues may arise.

**Comment by dcramble** [comment]
From my initial testing, it seems the issue is with the `blur` event. If I change the `setValue` call to use the optional `silent` argument, the problem goes away. It appears the `change` event is still firing when the value is actually changed, which is good.

**Original code:**

```
    this.$control_input.on('blur', function() {
        self.setValue(self.typingValue);
    });
```

**With proposed change:**

```
    this.$control_input.on('blur', function() {
        self.setValue(self.typingValue, true);
    });
```

**Comment by johnnyoshika** [comment]
This is a great plugin!  Can you suggest how this plugin can be enhanced so that a user can clear a selection?  Previously the <kbd>Backspace</kbd> key would do that, but that obviously won't work with this plugin.

**Comment by christor** [comment]
Is there something preventing this from being merged? This looks like a very nice plugin to include.

**Comment by GrumpyCrouton** [comment]
This gives me the error:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Selectize.self.trigger (selectize.js?plugins:917)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
    at Selectize.self.trigger (selectize.js?plugins:922)
```

**Pull request closed without merging**
