### PR TITLE
adding silent parameter to clearOptions

### LINKED ISSUE #832: clearOptions() silent option
I was just going to suggest adding the silent option to clearOptions(). I know this argument is already used elsewhere and it would benefit in situations where you would like to clear options on a selectbox because a dependency selectbox has changed but you do not want to fire onchange of the second selectbox...

### PR DESCRIPTION
**Pull request by bubb-rubb**
this commit fixes #832

### CODE REVIEW

**Comment by dattz** [comment]
Thanks bubb-rubb.

Why isn't this still merged? Really need this.

**Comment by millerbennett** [comment]
+1

**Review by doerig — APPROVED** [review]

**Comment by doerig** [comment]
+1

**Comment by mcfoton** [comment]
+1 need this in my life!

**Review by NitsanBaleli — APPROVED** [review]
much needed

**Comment by nmnandakishore** [comment]
+1, This is really much needed @joallard @brianreavis merging this will be very helpful.

**Review by joallard — CHANGES_REQUESTED** [review]
Thanks for the reviews and +1s. Here are my requested changes:

* [ ] Document parameter in `docs/`
* [ ] Document parameter in method comments
* [ ] Rebase commit on top of master

If the original PR author is not available, I'd accept an alternative PR with credit to @bubb-rubb.

**Comment by risadams** [comment]
superseded via PR #1553

**Pull request closed without merging**
