### PR TITLE
Add support for returning promise like objects from load.

### PR DESCRIPTION
**Pull request by topaxi**
This PR allows the load setting to return promises instead of calling the provided callback.

### CODE REVIEW

**Comment by topaxi** [comment]
If this feature is ever considered to be added to selectize, I will add tests and documentation for it, so this could be merged. Otherwise, feel free to close this PR.

**Comment by Ramblurr** [comment]
This is great! I also wish the render callbacks handled promises.

**Comment by joallard** [comment]
Is this an api-breaking change?

**Comment by topaxi** [comment]
This shouldn't be breaking, as long as nobody is returning a promise from the load function **and** calling the done callback, which is very unlikely.

**Comment by joallard** [comment]
I'm prepared to accept it. Can you add some test coverage?

**Comment by topaxi** [comment]
Rebased againts master and added some basic tests.

**Comment by topaxi** [comment]
Just going through a lot of my open PRs on Github. Anything left to do here from my side? Feel free to close this if you do not want to extend the selectize API with the proposed changes :)

**Pull request closed without merging**
