### PR TITLE
Few minor fix

### PR DESCRIPTION
**Pull request by fabienwnklr**
- Fix doc spelling error
- Fix right click on option select it (i find this not useful and confusing for the debug phase)
- Fix if text is empty but value not, set text as value

### CODE REVIEW

**Comment by risadams** [comment]
This PR has conflicts with the main branch; I haven't pulled it yet to see what is conflicting, but would you please be able to resolve those and resubmit?

**Comment by fabienwnklr** [comment]
sure, but i see no conflict ?
image

**Comment by risadams** [comment]
odd....  I do??

image

**Comment by fabienwnklr** [comment]
hum it's so weird lol, my fork is up to date.. 

image

**Comment by risadams** [comment]
got it.  it was only a problem with rebase,  I was able to squash and merge.

**Pull request merged**
