### PR TITLE
A more performant updateOriginalInput

### PR DESCRIPTION
**Pull request by deefour**
See #910 for context.

This is a new PR rebasing the last 3 years of changes in `master`.

### CODE REVIEW

**Comment by Pictor13** [comment]
I didn't review the code but the change looks interesting and useful. Good job 👍🏻

As you can there are errors with Travis CI.
In order to submit a pull request correctly, just the source code under `src/` directory should be modified, leaving untouched the code under `dist/` (distributed build).
This latter will be automatically updated with all the latest pull-requests, once there will be a new build release.

**Comment by deefour** [comment]
I don't plan on putting any more work into this.

**Comment by deefour** [comment]
It would be a shame for this PR to get auto-closed out by a Github action. While I cannot comment on a recent version of selectize, at the time the code in this PR was the difference between the dropdown box being unusable vs very performant.

As I mentioned 1.5 years ago, I won't be putting more work into this, but if it hasn't otherwise been fixed it'd be a shame not to not see the performance boost make it into a release.

**Comment by risadams** [comment]
Update on this PR,  I haven't merged it yet because it is causing tests to fail; however I'm not particularly sure that the original code is working quite correctly, so until I can determine what the correct behavior is, this is going to sit in the pending queue for a bit

**Comment by marianoesteban** [comment]
Escaping `value` and `label` with `escape_html()` in line 1742 makes the tests pass:
```js
fresh.push('<option value="' + escape_html(value) + '" selected="selected">' + escape_html(label) + '</option>');
```

**Comment by risadams** [comment]
Rebased, updated and merged in new PR #1895

**Pull request closed without merging**
