### PR TITLE
patch for #1141

### PR DESCRIPTION
**Pull request by ginlime**
#1141 remove highlight always on refresh before highlighting matched terms inline

### CODE REVIEW

**Comment by Darep** [comment]
I was experiencing the first character highlight bug (#1141) and can confirm this fixes it. Cheers! 🎉 👍

**Comment by joallard** [comment]
Sorry for not getting this, and thanks for the fix.

**Comment by coudrak** [comment]
I don't know how to use the patch,  when can we hope a merge with the master branch?

**Comment by Pictor13** [comment]
@joallard What is the reason you did decide to not merge this patch?

I think people from #1141 could benefit from it.

**Comment by joallard** [comment]
I have no idea.

**Comment by mcavalletto** [comment]
It looks like this patch was applied in 8da5b51ffb4bea4482206c8d6625d21cde3a58f0.

**Comment by ginlime** [comment]
HAHAHA!
Exactly the same code by other person is merged!

I'm done.

**Comment by joallard** [comment]
@ginlime Uh, hi?

I get that the other PR was made after yours, but let's keep in mind:

1. The goal is to make this library as good as possible, which either PRs did; it's not about getting huge credit for a change of a few lines, and
2. Managing and seeing clearly in a repo with 500 issues and 100+ PRs, with dozens piling up every week, and everyone wanting their pet issue fixed ASAP, is not exactly easy.

I'd suggest expressing your frustrations in a more constructive way next time. Thanks for stopping by.

**Pull request closed without merging**
