### PR TITLE
Add event 'item_before_remove' just before item is removed

### PR DESCRIPTION
**Pull request by giero**
It will be useful to add event just before item is removed, because removed element is detached from the document tree and - for example - it's impossible to get this items' parent.

### CODE REVIEW

**Comment by giero** [comment]
It's been a while ;) I would like to refresh this change :)

**Comment by giero** [comment]
@joallard Hi - any chance to merge this change to main repo?

**Comment by giero** [comment]
Is there any chance this could be reopened? I think it's still a valuable change.

**Comment by databyte** [comment]
@risadams - thoughts on reopening and looking at this since change with tests exists? I don't see any negative consequences of adding events to the process.

**Comment by risadams** [comment]
Agreed.  I'm open to reevaluating anything that is closed if there is interest

**Review by risadams — APPROVED** [review]

**Pull request merged**
