### PR TITLE
move jquery to peerDependencies

### PR DESCRIPTION
**Pull request by graingert**
https://nodejs.org/en/blog/npm/peer-dependencies/

### CODE REVIEW

**Comment by graingert** [comment]
Without this, it can cause selectize to try to use a different jquery than the main jquery

**Comment by graingert** [comment]
@joallard currently selictize is locked to jQuery `>=1.7.0 <2.0.0` for npm users. This pr opens that range up to include v2 and v3, and also ensures that only one version of jQuery is installed and used.

**Comment by graingert** [comment]
Fixes: https://github.com/selectize/selectize.js/issues/1277 I think

**Comment by matason** [comment]
Thanks @graingert, this fixes it for me.

**Comment by Kovah** [comment]
This would also solve [this jQuery security vulnerability](https://nodesecurity.io/advisories/328), which is patched in versions >= 3.0.0.

**Comment by graingert** [comment]
Nice, any chance of a release?

**Comment by joallard** [comment]
Done. 0.12.6

**Comment by Pictor13** [comment]
Great!

About jQuery, do we need to keep it in *bower.json* with that version range, for any retro-compatibility reason, or could we even remove it from there and rely on [bower-away](https://github.com/sheerun/bower-away) to move all the dependencies to package.json (Yarn/Npm) ?
Or do it manually, without bower-away.

Correct me if I am wrong, but I see no reason for having two conflicting definitions in bower and npm; is there?

**Comment by Pictor13** [comment]
Looks like there is an issue with forcing the jQuery version to ```^3.3.1``` (#1428).

I guess ```peerDependencies``` wins over ```dependencies``` and doesn't retain the ```^1.7``` compatibility.

**Comment by joallard** [comment]
Phasing out bower is something I agree we should go in the direction of, I'd be receptive to such PRs

**Pull request merged**
