### PR TITLE
Allow the `filter` option to be set for Sifter

### PR DESCRIPTION
**Pull request by u01jmg3**
- Allow the `filter` option to be set for Sifter
- Minor comment updates
- Fix ability to ignore hovering

### CODE REVIEW

**Comment by fabienwnklr** [comment]
@risadams Hi, this problem has not been patched, is it possible to merge this PR? Or just patch it ? If necessary i can contribute and make a new PR :)

**Comment by u01jmg3** [comment]
I'm happy to recreate this PR but it's almost 7 years old with no reply!

**Comment by risadams** [comment]
I am going to need to recreate this and ensure the conflicts are resolved.

**Comment by u01jmg3** [comment]
I've resolved the single conflict - let me know if you want me to rebase instead

**Comment by risadams** [comment]
updated and merged in #1866

**Pull request closed without merging**
