### PR TITLE
Dropdown direction autodetection.

### PR DESCRIPTION
**Pull request by impworks**
Implements the idea discusses in #29.

### CODE REVIEW

**Comment by kingsleyh** [comment]
why was this closed? did it not work very well?

**Comment by impworks** [comment]
@kingsleyh There's a (probably) better implementation in another pull request:

https://github.com/selectize/selectize.js/pull/1015

**Comment by kingsleyh** [comment]
Hey - I've implemented yours and it works great and it's simple 

The other one looks more complicated

**Comment by impworks** [comment]
@kingsleyh Glad that it works for you. My implementation worked for me as well, but had some cases uncovered (styles, etc.) which is why it was unsuitable to merge it.

**Pull request closed without merging**
